// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvy8ZG2QFJbIeqKLHtuTRNuyf5Nqab9Ko',
    appId: '1:398988127025:web:91bc18a6c3b2d8f5275e10',
    messagingSenderId: '398988127025',
    projectId: 'website-istana-bowling-proshop',
    authDomain: 'website-istana-bowling-proshop.firebaseapp.com',
    storageBucket: 'website-istana-bowling-proshop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5vLVcMWoe3pnrXNkMlvEmVfA3nNMuPUU',
    appId: '1:398988127025:android:3880f9218e0cfc61275e10',
    messagingSenderId: '398988127025',
    projectId: 'website-istana-bowling-proshop',
    storageBucket: 'website-istana-bowling-proshop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNYRlFYxQbueGN2pEpG9lWN0XhkwPHxxU',
    appId: '1:398988127025:ios:4d4b257622b31aac275e10',
    messagingSenderId: '398988127025',
    projectId: 'website-istana-bowling-proshop',
    storageBucket: 'website-istana-bowling-proshop.firebasestorage.app',
    iosBundleId: 'com.example.websiteIstanaBowlingProshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNYRlFYxQbueGN2pEpG9lWN0XhkwPHxxU',
    appId: '1:398988127025:ios:4d4b257622b31aac275e10',
    messagingSenderId: '398988127025',
    projectId: 'website-istana-bowling-proshop',
    storageBucket: 'website-istana-bowling-proshop.firebasestorage.app',
    iosBundleId: 'com.example.websiteIstanaBowlingProshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvy8ZG2QFJbIeqKLHtuTRNuyf5Nqab9Ko',
    appId: '1:398988127025:web:1e99d58c47aba589275e10',
    messagingSenderId: '398988127025',
    projectId: 'website-istana-bowling-proshop',
    authDomain: 'website-istana-bowling-proshop.firebaseapp.com',
    storageBucket: 'website-istana-bowling-proshop.firebasestorage.app',
  );
}
